spring:
  application:
    name: simpleBlog
  datasource:
    url: jdbc:mysql://localhost:3306/simpleBlog
    username: root
    password: Firengiz77
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  doc:
    swagger-ui:
      path: /simple-blog-documentation
    api-docs:
      path: /simple-blog-api-docs
logging:
  level:
    root: INFO
  file:
    name: logs/spring-boot-application.log
    path: logs
